### ISSUE TITLE
Installation error pip install click.tar.gz

### ISSUE THREAD

**Issue by kamoloff** [click-llc/click-integration-django#3]
Actually there is neither a `click.tar.gz` file nor a package.

**Comment by WJJamshiD** [comment]
The author meant to download the repo as an archive file then install using it.  
Firstly, go to the folder which is located the downloaded file in, unarchive it there, then  run the command:  pip install click-integration-django

**Comment by WJJamshiD** [comment]
You can download the repo as an archive file then install using it.
(Firstly, go to the folder which is located the downloaded file in, unarchive it there, then run the command: pip install click-integration-django)
